targets:
  $default:
    builders:
      dart_setters_getters_generator|setters_getters_builder:
        enabled: true

builders:
  setters_getters_builder:
    import: "package:dart_setters_getters_generator/src/generator.dart"
    builder_factories: ["settersGettersBuilder"]
    build_extensions: {".dart": [".gs.g.dart"]}
    auto_apply: dependents
    build_to: source
