name: dart_setters_getters_generator
description: A Dart code generator that creates ModelVariable wrappers for class fields, providing enhanced getter/setter functionality with change detection.
version: 1.0.0
repository: https://github.com/CrashKiki/dart_setters_getters_generator
homepage: https://github.com/CrashKiki/dart_setters_getters_generator

environment:
  sdk: ^3.8.1

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.0
  source_gen: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.0
